name: audiotrolley
favicon: null
layout_spectrum: 0.25113
typography_spectrum: 0.46823
title: 'all things audio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.3820124443154782
  rhythmicContrast: 0.3922264762222767
purpose: []
